// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlwwA-4gUJOI0_RoDoIPw5II90Wqp4mos',
    appId: '1:878749900384:web:d4df4c6374cbaadabeed05',
    messagingSenderId: '878749900384',
    projectId: 'pristine-disk-377217',
    authDomain: 'pristine-disk-377217.firebaseapp.com',
    storageBucket: 'pristine-disk-377217.appspot.com',
    measurementId: 'G-EQ7TPL771T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ4FP4p8fGOFLDQ-UmifwhBOIbN73zKgg',
    appId: '1:878749900384:android:c2a7471c1ab39f9abeed05',
    messagingSenderId: '878749900384',
    projectId: 'pristine-disk-377217',
    storageBucket: 'pristine-disk-377217.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhm9u7bMyu5oKDTYvHRGwVzpvm-p5Bx48',
    appId: '1:878749900384:ios:a3d6ee3122a11df3beed05',
    messagingSenderId: '878749900384',
    projectId: 'pristine-disk-377217',
    storageBucket: 'pristine-disk-377217.appspot.com',
    iosBundleId: 'com.example.exemploFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhm9u7bMyu5oKDTYvHRGwVzpvm-p5Bx48',
    appId: '1:878749900384:ios:a3d6ee3122a11df3beed05',
    messagingSenderId: '878749900384',
    projectId: 'pristine-disk-377217',
    storageBucket: 'pristine-disk-377217.appspot.com',
    iosBundleId: 'com.example.exemploFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlwwA-4gUJOI0_RoDoIPw5II90Wqp4mos',
    appId: '1:878749900384:web:d0a2b2b24f495097beed05',
    messagingSenderId: '878749900384',
    projectId: 'pristine-disk-377217',
    authDomain: 'pristine-disk-377217.firebaseapp.com',
    storageBucket: 'pristine-disk-377217.appspot.com',
    measurementId: 'G-ZF2BMKBXM9',
  );
}
